# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: vending_api
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module vending_api.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/vending_api.db
    volumes:
      - ./vending_api:/code/vending_api
      - ./db/:/db/
    ports:
      - "5000:5000"
